name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-wails:
    name: Build wails
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: darwin/universal
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build gon binary
        working-directory: cmd/gon
        run: go build
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cmd/gon/gon